### ISSUE TITLE
관리자 페이지 - 마크업

### ISSUE THREAD

**Issue by OneMoreBottlee** [codestates-seb/seb40_main_009#17]
1. 수행전
- 목표기한 : 11월 17일
- 필수 달성 항목:
  - [ ] 관리자 페이지 마크업
  - [ ] 챌린지 리스트
  - [ ] 당일 승인 관련
  - [ ] 유저 리스트 / 블랙 리스트
2. 수행후
- 달성일자 :
- 달성내용 :
  - [ ]
  - [ ]
  - [ ]
- 차후 개선사항 :
데이터 전송 방법

**Comment by msKim92** [comment]
안하기로 함
