### ISSUE TITLE
관리자 페이지 - 기능

### ISSUE THREAD

**Issue by OneMoreBottlee** [codestates-seb/seb40_main_009#27]
1. 수행전
- 시작조건 : api 통신 완료
- 목표기한 : 
- 필수 달성 항목:
  - [ ] 챌린지 / 유저 데이터 get & listing
  - [ ] 승인 관련 데이터 요청
  - [ ]
2. 수행후
- 달성일자 :
- 달성내용 :
  - [ ]
  - [ ]
  - [ ]
- 차후 개선사항 :

**Comment by msKim92** [comment]
안하기로 함
